---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting load generator - calling frontend every 2 seconds"
          while true; do
            curl -s http://frontend:8080/ || echo "request failed"
            sleep 2
          done
        resources:
          requests:
            memory: 16Mi
            cpu: 10m
          limits:
            memory: 32Mi
