apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/alloy
  ref:
    semver: ">=0.7.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: alloy
    namespace: flux-system

  values:
    alloy:
      configMap:
        content: |
          logging {
            level  = "info"
            format = "logfmt"
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "http://loki:3100/loki/api/v1/push"
            }
          }
