apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/prod/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
