apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/grafana
  ref:
    semver: ">=7.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: grafana
    namespace: flux-system

  values:
    adminUser: admin
    adminPassword: admin
    persistence:
      enabled: false
    service:
      type: ClusterIP
