apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/loki
  ref:
    semver: ">=6.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: default
spec:
  interval: 5m

  chartRef:
    kind: OCIRepository
    name: loki
    namespace: flux-system

  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false

      commonConfig:
        replication_factor: 1

      storage:
        type: filesystem
        bucketNames:
          chunks: chunks
          ruler: ruler
          admin: admin

      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    singleBinary:
      replicas: 1

    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0

    persistence:
      enabled: false
